# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lcop < Formula
  desc "CLI tool that drives GitHub Copilot CLI through a structured implementation workflow"
  homepage "https://github.com/smartcrabai/longcop"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.3/longcop_darwin_amd64.tar.gz"
      sha256 "7fe9e841646cb20314a461fce390599f8f85cfbb3e8725f3a8d0928d5228ccab"

      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.3/longcop_darwin_arm64.tar.gz"
      sha256 "7a722c6ed80e5748c283c7af20082a2fbe879fc0437b2a554995788d89e03118"

      define_method(:install) do
        bin.install "lcop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.3/longcop_linux_amd64.tar.gz"
      sha256 "c3bf8103b64dd95b5e801c8532162f0c0bc2ed5d34c327c6e600fc330df28c3a"
      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.3/longcop_linux_arm64.tar.gz"
      sha256 "01a3a08584a9b1d31f716366dd5948632c423aaebe84af363a66a399c2f4284c"
      define_method(:install) do
        bin.install "lcop"
      end
    end
  end
end
